### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by rimmesbe** [srob12/f1-3-c2p1-colmar-academy#3]
Your HTML looks pretty good. One thing that would really benefit you would be the incorporation of more HTML5 semantic tags: `<main> <section> <article> <aside> <figure>` and more. This will make  your code more readable and break up the sea of divs.
https://webflow.com/blog/html5-semantic-elements-and-webflow-the-essential-guide

https://github.com/srob12/f1-3-c2p1-colmar-academy/blob/master/Capstone%20Project/index.html

**Comment by srob12** [comment]
Thanks!
