### ISSUE TITLE
chained selectors

### ISSUE THREAD

**Issue by rimmesbe** [srob12/f1-3-c2p1-colmar-academy#4]
Try to limit your selector chains (how many selectors you use together to target a specific one). Here you are chaining 3, 4 and even 5 selectors together. This is way too many, the more you chain the less reusable and more rigid your code becomes. A slight change to the website will break these stylings. Try to limit yourself to 2 chained selectors and if you need more just make a new class for that component.

https://github.com/srob12/f1-3-c2p1-colmar-academy/blob/master/Capstone%20Project/style.css#L364

**Comment by srob12** [comment]
Thanks!
