### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by rimmesbe** [srob12/f1-3-c2p1-colmar-academy#5]
You have written a lot of CSS and yet the site looks pretty far from being complete. You may want to concentrate on one section at a time. Get the header working and formatted, then the next section and so on. Rather than trying to slightly style each section a little bit at a time.

https://github.com/srob12/f1-3-c2p1-colmar-academy/blob/master/Capstone%20Project/style.css

**Comment by srob12** [comment]
Thanks for the good tips! I'll get better, this is all the first time for me....
