### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [srob12/f1-3-c2p1-colmar-academy#6]
Grade: Needs improvement

Summary: You have a good foundation here, but you have a ways to go. You used some good techniques and kept your code well organized. Take a look at the issues I created for some best practice tips as well as some new techniques you can start applying. I think you maybe tried to do too much too fast in the case of styling. Take it one step at a time. Often once you complete one section the code you have written will help you in the future sections. Keep at it, just takes time and practice.

**Comment by srob12** [comment]
Thanks for all of your tips and feedback!!!
